"""new_db_structure

Revision ID: 7f1deaa475c2
Revises: 
Create Date: 2025-01-24 18:00:42.947355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f1deaa475c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_new')
    op.add_column('challenge_participants', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('challenge_participants', 'joined_at')
    op.add_column('running_log', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('running_log', sa.Column('external_source', sa.String(length=50), nullable=True))
    op.add_column('running_log', sa.Column('detailed_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('running_log', sa.Column('splits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('running_log', sa.Column('elevation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('running_log', sa.Column('average_heartrate', sa.DECIMAL(), nullable=True))
    op.add_column('running_log', sa.Column('max_heartrate', sa.DECIMAL(), nullable=True))
    op.add_column('running_log', sa.Column('perceived_effort', sa.Integer(), nullable=True))
    op.add_column('running_log', sa.Column('training_load', sa.DECIMAL(), nullable=True))
    op.add_column('running_log', sa.Column('recovery_time', sa.Interval(), nullable=True))
    op.add_column('yearly_archive', sa.Column('total_km', sa.Float(), nullable=True))
    op.add_column('yearly_archive', sa.Column('total_users', sa.Integer(), nullable=True))
    op.add_column('yearly_archive', sa.Column('goal_achieved', sa.Float(), nullable=True))
    op.drop_column('yearly_archive', 'yearly_goal')
    op.drop_column('yearly_archive', 'yearly_progress')
    op.drop_column('yearly_archive', 'username')
    op.drop_column('yearly_archive', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yearly_archive', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('yearly_archive', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('yearly_archive', sa.Column('yearly_progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('yearly_archive', sa.Column('yearly_goal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('yearly_archive', 'goal_achieved')
    op.drop_column('yearly_archive', 'total_users')
    op.drop_column('yearly_archive', 'total_km')
    op.drop_column('running_log', 'recovery_time')
    op.drop_column('running_log', 'training_load')
    op.drop_column('running_log', 'perceived_effort')
    op.drop_column('running_log', 'max_heartrate')
    op.drop_column('running_log', 'average_heartrate')
    op.drop_column('running_log', 'elevation_data')
    op.drop_column('running_log', 'splits')
    op.drop_column('running_log', 'detailed_metrics')
    op.drop_column('running_log', 'external_source')
    op.drop_column('running_log', 'external_id')
    op.add_column('challenge_participants', sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('challenge_participants', 'completed')
    op.create_table('alembic_version_new',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_new_pkc')
    )
    # ### end Alembic commands ###
